FROM python:3.10.9

WORKDIR /mlflow/

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt && \
  rm requirements.txt

EXPOSE 5000

CMD mlflow server --host 0.0.0.0 --port 5000

# docker run -p 5000:5000 --name mlflow-server mlflow