FROM python:3.10.9

WORKDIR /mlflow/

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt && \
  rm requirements.txt

EXPOSE 5000

#CMD mlflow server --host 0.0.0.0 --port 5000
CMD ["gunicorn", "-w", "2", "-b", "0.0.0.0:5000", "--timeout", "180", "mlflow.server:app"]
# docker run -p 5000:5000 --name mlflow-server mlflow