# Generated by Django 5.0.7 on 2024-07-31 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MER_NORM',
            fields=[
                ('idData', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('CO', models.DecimalField(decimal_places=12, max_digits=13)),
                ('NO', models.DecimalField(decimal_places=12, max_digits=13)),
                ('NOX', models.DecimalField(decimal_places=12, max_digits=13)),
                ('NO2', models.DecimalField(decimal_places=12, max_digits=13)),
                ('O3', models.DecimalField(decimal_places=12, max_digits=13)),
                ('PM10', models.DecimalField(decimal_places=12, max_digits=13)),
                ('PM25', models.DecimalField(decimal_places=12, max_digits=13)),
                ('RH', models.DecimalField(decimal_places=2, max_digits=3)),
                ('SO2', models.DecimalField(decimal_places=12, max_digits=13)),
                ('TMP', models.DecimalField(decimal_places=12, max_digits=13)),
                ('WDR', models.DecimalField(decimal_places=12, max_digits=13)),
                ('WSP', models.DecimalField(decimal_places=12, max_digits=13)),
                ('year', models.IntegerField()),
                ('day', models.IntegerField()),
                ('hora', models.IntegerField()),
                ('minutos', models.IntegerField()),
                ('traffic', models.DecimalField(decimal_places=12, max_digits=13)),
            ],
        ),
        migrations.CreateModel(
            name='PED_NORM',
            fields=[
                ('idData', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('CO', models.DecimalField(decimal_places=12, max_digits=13)),
                ('NO', models.DecimalField(decimal_places=12, max_digits=13)),
                ('NOX', models.DecimalField(decimal_places=12, max_digits=13)),
                ('NO2', models.DecimalField(decimal_places=12, max_digits=13)),
                ('O3', models.DecimalField(decimal_places=12, max_digits=13)),
                ('PM10', models.DecimalField(decimal_places=12, max_digits=13)),
                ('PM25', models.DecimalField(decimal_places=12, max_digits=13)),
                ('RH', models.DecimalField(decimal_places=2, max_digits=3)),
                ('SO2', models.DecimalField(decimal_places=12, max_digits=13)),
                ('TMP', models.DecimalField(decimal_places=12, max_digits=13)),
                ('WDR', models.DecimalField(decimal_places=12, max_digits=13)),
                ('WSP', models.DecimalField(decimal_places=12, max_digits=13)),
                ('year', models.IntegerField()),
                ('day', models.IntegerField()),
                ('hora', models.IntegerField()),
                ('minutos', models.IntegerField()),
                ('traffic', models.DecimalField(decimal_places=12, max_digits=13)),
            ],
        ),
        migrations.CreateModel(
            name='UIZ_NORM',
            fields=[
                ('idData', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('CO', models.DecimalField(decimal_places=12, max_digits=13)),
                ('NO', models.DecimalField(decimal_places=12, max_digits=13)),
                ('NOX', models.DecimalField(decimal_places=12, max_digits=13)),
                ('NO2', models.DecimalField(decimal_places=12, max_digits=13)),
                ('O3', models.DecimalField(decimal_places=12, max_digits=13)),
                ('PM10', models.DecimalField(decimal_places=12, max_digits=13)),
                ('PM25', models.DecimalField(decimal_places=12, max_digits=13)),
                ('RH', models.DecimalField(decimal_places=2, max_digits=3)),
                ('SO2', models.DecimalField(decimal_places=12, max_digits=13)),
                ('TMP', models.DecimalField(decimal_places=12, max_digits=13)),
                ('WDR', models.DecimalField(decimal_places=12, max_digits=13)),
                ('WSP', models.DecimalField(decimal_places=12, max_digits=13)),
                ('year', models.IntegerField()),
                ('day', models.IntegerField()),
                ('hora', models.IntegerField()),
                ('minutos', models.IntegerField()),
                ('traffic', models.DecimalField(decimal_places=12, max_digits=13)),
            ],
        ),
    ]
