# Generated by Django 5.0.7 on 2024-08-06 18:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("apiCalidadAire", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="mer_norm",
            old_name="hora",
            new_name="hour",
        ),
        migrations.RenameField(
            model_name="mer_norm",
            old_name="minutos",
            new_name="minutes",
        ),
        migrations.RenameField(
            model_name="ped_norm",
            old_name="hora",
            new_name="hour",
        ),
        migrations.RenameField(
            model_name="ped_norm",
            old_name="minutos",
            new_name="minutes",
        ),
        migrations.RenameField(
            model_name="uiz_norm",
            old_name="hora",
            new_name="hour",
        ),
        migrations.RenameField(
            model_name="uiz_norm",
            old_name="minutos",
            new_name="minutes",
        ),
    ]
