from django.db import models

# Create your models here.

class PED_NORM(models.Model):
    idData = models.AutoField(primary_key=True)
    date = models.DateField()
    CO = models.DecimalField(max_digits=13, decimal_places=12)
    NO = models.DecimalField(max_digits=13, decimal_places=12)
    NOX = models.DecimalField(max_digits=13, decimal_places=12)
    NO2 = models.DecimalField(max_digits=13, decimal_places=12)
    O3 = models.DecimalField(max_digits=13, decimal_places=12)
    PM10 = models.DecimalField(max_digits=13, decimal_places=12)
    PM25 = models.DecimalField(max_digits=13, decimal_places=12)
    RH = models.DecimalField(max_digits=13, decimal_places=12)
    SO2 = models.DecimalField(max_digits=13, decimal_places=12)
    TMP = models.DecimalField(max_digits=13, decimal_places=12)
    WDR = models.DecimalField(max_digits=13, decimal_places=12)
    WSP = models.DecimalField(max_digits=13, decimal_places=12)
    year = models.IntegerField()
    month = models.IntegerField(default='0')
    day = models.IntegerField()
    hour = models.IntegerField()
    minutes = models.IntegerField()
    traffic = models.DecimalField(max_digits=13, decimal_places=12, default='0.00')

class PED_NORM_24_CLASSIF(models.Model):
    idData = models.AutoField(primary_key=True)
    date = models.DateField()
    CO = models.DecimalField(max_digits=13, decimal_places=12)
    NO = models.DecimalField(max_digits=13, decimal_places=12)
    NOX = models.DecimalField(max_digits=13, decimal_places=12)
    NO2 = models.DecimalField(max_digits=13, decimal_places=12)
    O3 = models.DecimalField(max_digits=13, decimal_places=12)
    PM10 = models.DecimalField(max_digits=13, decimal_places=12)
    PM25 = models.DecimalField(max_digits=13, decimal_places=12)
    RH = models.DecimalField(max_digits=13, decimal_places=12)
    SO2 = models.DecimalField(max_digits=13, decimal_places=12)
    TMP = models.DecimalField(max_digits=13, decimal_places=12)
    WDR = models.DecimalField(max_digits=13, decimal_places=12)
    WSP = models.DecimalField(max_digits=13, decimal_places=12)
    year = models.IntegerField()
    month = models.IntegerField(default='0')
    day = models.IntegerField()
    hour = models.IntegerField()
    minutes = models.IntegerField()
    traffic = models.DecimalField(max_digits=13, decimal_places=12, default='0.00')
    O3_24 = models.DecimalField(max_digits=13, decimal_places=12)
    nivelCalidad = models.IntegerField()

class MER_NORM(models.Model):
    idData = models.AutoField(primary_key=True)
    date = models.DateField()
    CO = models.DecimalField(max_digits=13, decimal_places=12)
    NO = models.DecimalField(max_digits=13, decimal_places=12)
    NOX = models.DecimalField(max_digits=13, decimal_places=12)
    NO2 = models.DecimalField(max_digits=13, decimal_places=12)
    O3 = models.DecimalField(max_digits=13, decimal_places=12)
    PM10 = models.DecimalField(max_digits=13, decimal_places=12)
    PM25 = models.DecimalField(max_digits=13, decimal_places=12)
    RH = models.DecimalField(max_digits=13, decimal_places=12)
    SO2 = models.DecimalField(max_digits=13, decimal_places=12)
    TMP = models.DecimalField(max_digits=13, decimal_places=12)
    WDR = models.DecimalField(max_digits=13, decimal_places=12)
    WSP = models.DecimalField(max_digits=13, decimal_places=12)
    year = models.IntegerField()
    month = models.IntegerField(default='0')
    day = models.IntegerField()
    hour = models.IntegerField()
    minutes = models.IntegerField()
    traffic = models.DecimalField(max_digits=13, decimal_places=12, default='0.00')

class MER_NORM_24_CLASSIF(models.Model):
    idData = models.AutoField(primary_key=True)
    date = models.DateField()
    CO = models.DecimalField(max_digits=13, decimal_places=12)
    NO = models.DecimalField(max_digits=13, decimal_places=12)
    NOX = models.DecimalField(max_digits=13, decimal_places=12)
    NO2 = models.DecimalField(max_digits=13, decimal_places=12)
    O3 = models.DecimalField(max_digits=13, decimal_places=12)
    PM10 = models.DecimalField(max_digits=13, decimal_places=12)
    PM25 = models.DecimalField(max_digits=13, decimal_places=12)
    RH = models.DecimalField(max_digits=13, decimal_places=12)
    SO2 = models.DecimalField(max_digits=13, decimal_places=12)
    TMP = models.DecimalField(max_digits=13, decimal_places=12)
    WDR = models.DecimalField(max_digits=13, decimal_places=12)
    WSP = models.DecimalField(max_digits=13, decimal_places=12)
    year = models.IntegerField()
    month = models.IntegerField(default='0')
    day = models.IntegerField()
    hour = models.IntegerField()
    minutes = models.IntegerField()
    traffic = models.DecimalField(max_digits=13, decimal_places=12, default='0.00')
    O3_24 = models.DecimalField(max_digits=13, decimal_places=12)
    nivelCalidad = models.IntegerField()
    

class UIZ_NORM(models.Model):
    idData = models.AutoField(primary_key=True)
    date = models.DateField()
    CO = models.DecimalField(max_digits=13, decimal_places=12)
    NO = models.DecimalField(max_digits=13, decimal_places=12)
    NOX = models.DecimalField(max_digits=13, decimal_places=12)
    NO2 = models.DecimalField(max_digits=13, decimal_places=12)
    O3 = models.DecimalField(max_digits=13, decimal_places=12)
    PM10 = models.DecimalField(max_digits=13, decimal_places=12)
    PM25 = models.DecimalField(max_digits=13, decimal_places=12)
    RH = models.DecimalField(max_digits=13, decimal_places=12)
    SO2 = models.DecimalField(max_digits=13, decimal_places=12)
    TMP = models.DecimalField(max_digits=13, decimal_places=12)
    WDR = models.DecimalField(max_digits=13, decimal_places=12)
    WSP = models.DecimalField(max_digits=13, decimal_places=12)
    year = models.IntegerField()
    month = models.IntegerField(default='0')
    day = models.IntegerField()
    hour = models.IntegerField()
    minutes = models.IntegerField()
    traffic = models.DecimalField(max_digits=13, decimal_places=12,  default='0.00')

class UIZ_NORM_24_CLASSIF(models.Model):
    idData = models.AutoField(primary_key=True)
    date = models.DateField()
    CO = models.DecimalField(max_digits=13, decimal_places=12)
    NO = models.DecimalField(max_digits=13, decimal_places=12)
    NOX = models.DecimalField(max_digits=13, decimal_places=12)
    NO2 = models.DecimalField(max_digits=13, decimal_places=12)
    O3 = models.DecimalField(max_digits=13, decimal_places=12)
    PM10 = models.DecimalField(max_digits=13, decimal_places=12)
    PM25 = models.DecimalField(max_digits=13, decimal_places=12)
    RH = models.DecimalField(max_digits=13, decimal_places=12)
    SO2 = models.DecimalField(max_digits=13, decimal_places=12)
    TMP = models.DecimalField(max_digits=13, decimal_places=12)
    WDR = models.DecimalField(max_digits=13, decimal_places=12)
    WSP = models.DecimalField(max_digits=13, decimal_places=12)
    year = models.IntegerField()
    month = models.IntegerField(default='0')
    day = models.IntegerField()
    hour = models.IntegerField()
    minutes = models.IntegerField()
    traffic = models.DecimalField(max_digits=13, decimal_places=12,  default='0.00')
    O3_24 = models.DecimalField(max_digits=13, decimal_places=12)
    nivelCalidad = models.IntegerField()

class PED_15M(models.Model):
    idData = models.AutoField(primary_key=True)
    date = models.DateField()
    CO = models.DecimalField(max_digits=16, decimal_places=6)
    NO = models.DecimalField(max_digits=16, decimal_places=6)
    NOX = models.DecimalField(max_digits=16, decimal_places=6)
    NO2 = models.DecimalField(max_digits=16, decimal_places=6)
    O3 = models.DecimalField(max_digits=16, decimal_places=6)
    PM10 = models.DecimalField(max_digits=16, decimal_places=6)
    PM25 = models.DecimalField(max_digits=16, decimal_places=6)
    RH = models.DecimalField(max_digits=16, decimal_places=6)
    SO2 = models.DecimalField(max_digits=16, decimal_places=6)
    TMP = models.DecimalField(max_digits=16, decimal_places=6)
    WDR = models.DecimalField(max_digits=16, decimal_places=6)
    WSP = models.DecimalField(max_digits=16, decimal_places=6)
    year = models.IntegerField()
    month = models.IntegerField(default='0')
    day = models.IntegerField()
    hour = models.IntegerField()
    minutes = models.IntegerField()
    traffic = models.DecimalField(max_digits=16, decimal_places=6, default='0.00')


class MER_15M(models.Model):
    idData = models.AutoField(primary_key=True)
    date = models.DateField()
    CO = models.DecimalField(max_digits=16, decimal_places=6)
    NO = models.DecimalField(max_digits=16, decimal_places=6)
    NOX = models.DecimalField(max_digits=16, decimal_places=6)
    NO2 = models.DecimalField(max_digits=16, decimal_places=6)
    O3 = models.DecimalField(max_digits=16, decimal_places=6)
    PM10 = models.DecimalField(max_digits=16, decimal_places=6)
    PM25 = models.DecimalField(max_digits=16, decimal_places=6)
    RH = models.DecimalField(max_digits=16, decimal_places=6)
    SO2 = models.DecimalField(max_digits=16, decimal_places=6)
    TMP = models.DecimalField(max_digits=16, decimal_places=6)
    WDR = models.DecimalField(max_digits=16, decimal_places=6)
    WSP = models.DecimalField(max_digits=16, decimal_places=6)
    year = models.IntegerField()
    month = models.IntegerField(default='0')
    day = models.IntegerField(default='0')
    hour = models.IntegerField()
    minutes = models.IntegerField()
    traffic = models.DecimalField(max_digits=16, decimal_places=6, default='0.00')
    

class UIZ_15M(models.Model):
    idData = models.AutoField(primary_key=True)
    date = models.DateField()
    CO = models.DecimalField(max_digits=16, decimal_places=6)
    NO = models.DecimalField(max_digits=16, decimal_places=6)
    NOX = models.DecimalField(max_digits=16, decimal_places=6)
    NO2 = models.DecimalField(max_digits=16, decimal_places=6)
    O3 = models.DecimalField(max_digits=16, decimal_places=6)
    PM10 = models.DecimalField(max_digits=16, decimal_places=6)
    PM25 = models.DecimalField(max_digits=16, decimal_places=6)
    RH = models.DecimalField(max_digits=16, decimal_places=6)
    SO2 = models.DecimalField(max_digits=16, decimal_places=6)
    TMP = models.DecimalField(max_digits=16, decimal_places=6)
    WDR = models.DecimalField(max_digits=16, decimal_places=6)
    WSP = models.DecimalField(max_digits=16, decimal_places=6)
    year = models.IntegerField()
    month = models.IntegerField(default='0')
    day = models.IntegerField()
    hour = models.IntegerField()
    minutes = models.IntegerField()
    traffic = models.DecimalField(max_digits=16, decimal_places=6,  default='0.00')

class estacionesCAME(models.Model):
    idEstacion = models.AutoField(primary_key=True)
    key = models.CharField(max_length=5)
    name = models.CharField(max_length=100)
    ID = models.CharField(max_length=50)
    O3 = models.IntegerField(default='0', null = True)
    CO = models.IntegerField(default='0', null = True)
    SO2 = models.IntegerField(default='0', null = True)
    NO2 = models.IntegerField(default='0', null = True)
    PM10 = models.IntegerField(default='0', null = True)
    PM25 = models.IntegerField(default='0', null = True)
    status = models.CharField(max_length=50)
    date = models.DateField()
    municipality = models.CharField(max_length=100)
    state = models.CharField(max_length=100)
    altitude = models.CharField(max_length=100)
    latitude = models.CharField(max_length=100)
    longitude = models.CharField(max_length=100)
    address = models.CharField(max_length=500)
    website = models.CharField(max_length=200)
    notes = models.CharField(max_length=300)
    traffic = models.CharField(max_length=5)
    xTileIn = models.CharField(max_length=50)
    yTileIn = models.CharField(max_length=50)


class PED_PROM_HR(models.Model):
    idData = models.AutoField(primary_key=True)
    date = models.DateField()
    CO = models.DecimalField(max_digits=16, decimal_places=6)
    NO = models.DecimalField(max_digits=16, decimal_places=6)
    NOX = models.DecimalField(max_digits=16, decimal_places=6)
    NO2 = models.DecimalField(max_digits=16, decimal_places=6)
    O3 = models.DecimalField(max_digits=16, decimal_places=6)
    PM10 = models.DecimalField(max_digits=16, decimal_places=6)
    PM25 = models.DecimalField(max_digits=16, decimal_places=6)
    RH = models.DecimalField(max_digits=16, decimal_places=6)
    SO2 = models.DecimalField(max_digits=16, decimal_places=6)
    TMP = models.DecimalField(max_digits=16, decimal_places=6)
    WDR = models.DecimalField(max_digits=16, decimal_places=6)
    WSP = models.DecimalField(max_digits=16, decimal_places=6)
    year = models.IntegerField()
    month = models.IntegerField(default='0')
    day = models.IntegerField()
    hour = models.IntegerField()
    minutes = models.IntegerField()
    traffic = models.DecimalField(max_digits=16, decimal_places=6, default='0.00')


class MER_PROM_HR(models.Model):
    idData = models.AutoField(primary_key=True)
    date = models.DateField()
    CO = models.DecimalField(max_digits=16, decimal_places=6)
    NO = models.DecimalField(max_digits=16, decimal_places=6)
    NOX = models.DecimalField(max_digits=16, decimal_places=6)
    NO2 = models.DecimalField(max_digits=16, decimal_places=6)
    O3 = models.DecimalField(max_digits=16, decimal_places=6)
    PM10 = models.DecimalField(max_digits=16, decimal_places=6)
    PM25 = models.DecimalField(max_digits=16, decimal_places=6)
    RH = models.DecimalField(max_digits=16, decimal_places=6)
    SO2 = models.DecimalField(max_digits=16, decimal_places=6)
    TMP = models.DecimalField(max_digits=16, decimal_places=6)
    WDR = models.DecimalField(max_digits=16, decimal_places=6)
    WSP = models.DecimalField(max_digits=16, decimal_places=6)
    year = models.IntegerField()
    month = models.IntegerField(default='0')
    day = models.IntegerField()
    hour = models.IntegerField()
    minutes = models.IntegerField()
    traffic = models.DecimalField(max_digits=16, decimal_places=6, default='0.00')
    

class UIZ_PROM_HR(models.Model):
    idData = models.AutoField(primary_key=True)
    date = models.DateField()
    CO = models.DecimalField(max_digits=16, decimal_places=6)
    NO = models.DecimalField(max_digits=16, decimal_places=6)
    NOX = models.DecimalField(max_digits=16, decimal_places=6)
    NO2 = models.DecimalField(max_digits=16, decimal_places=6)
    O3 = models.DecimalField(max_digits=16, decimal_places=6)
    PM10 = models.DecimalField(max_digits=16, decimal_places=6)
    PM25 = models.DecimalField(max_digits=16, decimal_places=6)
    RH = models.DecimalField(max_digits=16, decimal_places=6)
    SO2 = models.DecimalField(max_digits=16, decimal_places=6)
    TMP = models.DecimalField(max_digits=16, decimal_places=6)
    WDR = models.DecimalField(max_digits=16, decimal_places=6)
    WSP = models.DecimalField(max_digits=16, decimal_places=6)
    year = models.IntegerField()
    month = models.IntegerField(default='0')
    day = models.IntegerField()
    hour = models.IntegerField()
    minutes = models.IntegerField()
    traffic = models.DecimalField(max_digits=16, decimal_places=6,  default='0.00')

class EstatusCalidad(models.Model):
    idEstatus = models.AutoField(primary_key=True)
    descEstatus = models.CharField(max_length=50)
    recomendacion = models.CharField(max_length=100)
    descColor = models.CharField(max_length=50)
    valorColor = models.CharField(max_length=10)

class Contaminantes(models.Model):
    idContaminante = models.AutoField(primary_key=True)
    Contaminante = models.CharField(max_length=50, default="")
    descContaminante = models.CharField(max_length=50)

class Unidades(models.Model):
    idUnidad = models.AutoField(primary_key=True)
    descUnidad = models.CharField(max_length=50)

class Prediccion(models.Model):
    idPrediccion = models.AutoField(primary_key=True)
    Estacion =  models.ForeignKey(estacionesCAME, on_delete=models.CASCADE, blank=False, null=False)
    Contaminante = models.ForeignKey(Contaminantes, on_delete=models.CASCADE, blank=False, null=False)
    valorContaminante = models.DecimalField(max_digits=6, decimal_places=4)
    Unidad = models.ForeignKey(Unidades, on_delete=models.CASCADE, blank=False, null=False)
    Estatus = models.ForeignKey(EstatusCalidad, on_delete=models.CASCADE, blank=False, null=False)
    fechaPrediccion = models.DateTimeField(auto_now_add=True)

    